files:
  - source: /mastodon/src/main/res/values/strings.xml
    translation: /mastodon/src/main/res/values-%android_code%/strings.xml
  - source: /fastlane/metadata/android/en-US/*.txt
    translation: /fastlane/metadata/android/%two_letters_code%/%original_file_name%
    ignore:
      - /fastlane/metadata/android/en-US/title.txt
